apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: jupyter-ns
spec:
  selector:
    app: jupyter
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
