name: CICD for jupyter 

on: 
 push:
   branches: [main]

env:
  IMAGE_NAME: "jupyter-test"
  IMAGE_TAG: ${{ github.run_number }}
  REGISTRY: docker.io
  NAMESPACE: jupyter-ns

jobs:
  build:
    runs-on: self-hosted
    env:
      DOCKER_CLI_HINTS: disabled
    steps:
      - name: Checkout code 
        uses: actions/checkout@v6.0.2
      - name: Docker Login
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy using Helm
        run: |
          helm upgrade --install jupyter helm/jupyter \
            --namespace $NAMESPACE \
            --create-namespace \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG
